#include "stdafx.h"

//global variables

 //MOG2 Background subtractor
int keyboard;
MOGDetection::MOGDetection() {

	pMOG = cv::bgsegm::createBackgroundSubtractorMOG(); //MOG approach
	pMOG2 = cv::createBackgroundSubtractorMOG2(); //MOG2 approach
}
MOGDetection::~MOGDetection() {

}
cv::Mat MOGDetection::detect(cv::Mat &frame) {
	//cv::VideoCapture capture;
	//capture = CaptureVideo::getInstance();
	//if (!capture.open(0))
		//return;// false;
	//cv::namedWindow("Frame");
	//cv::namedWindow("FG Mask MOG");
	//cv::namedWindow("FG Mask MOG 2");

	//cv::Mat fgMaskMOG; //fg mask fg mask generated by MOG2 method
	cv::Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method

	//create Background Subtractor objects
	//while ((char)keyboard != 'q' && (char)keyboard != 27) {
		//read the current frame
		if (frame.empty()) {
			std::cerr << "Unable to read next frame." << std::endl;
			std::cerr << "Exiting..." << std::endl;
			exit(EXIT_FAILURE);
		}
		//update the background model
		pMOG2->apply(frame, fgMaskMOG2);
		//pMOG->apply(frame, fgMaskMOG);
		//get the frame number and write it on the current frame
		//std::stringstream ss;
		//rectangle(frame, cv::Point(10, 2), cv::Point(100, 20),
		//	cv::Scalar(255, 255, 255), -1);
		//ss << frame;//capture.get(cv::CAP_PROP_POS_FRAMES);
		//std::string frameNumberString = ss.str();
		//putText(frame, frameNumberString.c_str(), cv::Point(15, 15),
		//	cv::FONT_HERSHEY_SIMPLEX, 0.5, cv::Scalar(0, 0, 0));
		//show the current frame and the fg masks
		//imshow("Frame", frame);
	//cv::imshow("FG Mask MOG", fgMaskMOG);
		//imshow("FG Mask MOG 2", fgMaskMOG2);
		//get the input from the keyboard
	//}
	//delete capture object
	//capture.release();
	//return;// false;
		return fgMaskMOG2;
}